/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include"main.h"




// ----------------------------------------------------------------------------


int main(void)
{
	Za3bola_Animations_Init();
	Za3bola_WelcomeMessage();
    /* Loop forever */
	while(1){
		Za3bola_Animation1();
		Za3bola_Animation2();
		Za3bola_Animation3();
	}
}
