/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include"main.h"

// ----------------------------------------------------------------------------
void IR_Handler(void){
	if(IR_u32GetReceivedData() == IR_TV_REMOTE_1)
	{
		LedAnimation_Flashing();
	}
	else if(IR_u32GetReceivedData() == IR_TV_REMOTE_2)
	{
		LedAnimation_Snake();
	}
	else if(IR_u32GetReceivedData() == IR_TV_REMOTE_3)
	{
		LedAnimation_PingPong();
	}
	else if(IR_u32GetReceivedData() == IR_TV_REMOTE_4)
	{
		LedAnimation_Fat7yYaWarda();
	}
	else if(IR_u32GetReceivedData() == IR_TV_REMOTE_5)
	{
		LedAnimation_2aflyYaWarda();
	}

}

int main(void)
{
	LedAnimation_8Leds_Init();
	IR_voidInit(&IR_Config,IR_Handler);
    /* Loop forever */
	while(1)
	{


	}
}
